kind: MLApp
metadata:
  name: movidius-facenet
spec:
  default_mount_path: /notebooks
  default_read_only: false
  package_manager: pip3
  packages:
  - manager: pip3
  tasks:
  - name: align-images
    resources:
    - command: export PYTHONPATH=$SRC_DIR:$PYTHONPATH; python align/align_dataset_mtcnn.py
        $CODE_DIR/training_faces $CODE_DIR/faces_160 --image_size 160  --margin 32
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: train-classifier
    resources:
    - command: python classifier.py TRAIN $CODE_DIR/faces_160 $MODEL_DIR/20180402-114759.pb $TRAINING_DIR/classifier.pkl
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: validate-classifier
    resources:
    - command: python classifier.py CLASSIFY $CODE_DIR/faces_160 $MODEL_DIR/20180402-114759.pb $TRAINING_DIR/classifier.pkl --upload-model --upload-threshold 0.9
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: pipeline
    resources:
    - command: python pipeline.py
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: pnet-graph
    resources:
    - command: python3 movidius_converter.py --pnet --training_dir /tmp --do_push
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: onet-graph
    resources:
    - command: python3 movidius_converter.py --onet --training_dir /tmp --do_push
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: rnet-graph
    resources:
    - command: python3 movidius_converter.py --rnet --training_dir /tmp --do_push
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: fnet-graph
    resources:
    - command: python3 movidius_converter.py --facenet --training_dir /tmp --do_push
        --model_base_path $MODEL_DIR
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: facenet-graph
    resources:
    - command: python3 movidius_converter.py --all --training_dir /tmp --do_push --model_base_path
        $MODEL_DIR
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  uix:
  - default_volume_mapping: true
    displayName: Jupyter
    images:
      cpu: kuberlab/movidius-test
    name: jupyter
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 64Mi
  volumes:
  - clusterStorage: '{{ .storage.value }}'
    name: training
  - gitRepo:
      repository: https://github.com/kuberlab/facenet
    name: src
    subPath: facenet/src
  - clusterStorage: '{{ .storage.value }}'
    isLibDir: true
    name: lib
  - clusterStorage: '{{ .storage.value }}'
    mountPath: /notebooks
    name: code
    subPath: code
  - datasetFS:
      dataset: facenet-pretrained
      version: 2018.4.2-vgg
      workspace: kuberlab-demo
    name: model
