kind: MLApp
metadata:
  name: movidius-facenet
revision:
  author: "1"
  author_email: agunin@3playnet.com
  author_name: Alexander Gunin
  branch: master
  comment: Execute task pipeline 2018-07-19 21:54:46
spec:
  default_mount_path: /notebooks
  default_read_only: false
  package_manager: pip3
  packages:
  - manager: pip3
  tasks:
  - name: align-images
    resources:
    - command: export PYTHONPATH=$SRC_DIR:$PYTHONPATH; python align/align_dataset_mtcnn.py
        $CODE_DIR/training_faces $CODE_DIR/faces_160 --image_size 160  --margin 32
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      is_permanent: false
      maxRestartCount: 0
      name: worker
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: train-classifier
    resources:
    - command: python classifier.py TRAIN $CODE_DIR/faces_160 $MODEL_DIR/20180402-114759.pb
        $TRAINING_DIR/classifier.pkl
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      is_permanent: false
      maxRestartCount: 0
      name: worker
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: validate-classifier
    resources:
    - command: python classifier.py CLASSIFY $CODE_DIR/faces_160 $MODEL_DIR/20180402-114759.pb
        $TRAINING_DIR/classifier.pkl --upload-model --upload-threshold 0.9
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      is_permanent: false
      maxRestartCount: 0
      name: worker
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: pipeline
    resources:
    - command: python pipeline.py
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      is_permanent: false
      maxRestartCount: 0
      name: worker
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: pnet-grapth
    resources:
    - command: python3 movidius_converter.py --pnet --training_dir /tmp --do_push
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      is_permanent: false
      maxRestartCount: 0
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: onet-grapth
    resources:
    - command: python3 movidius_converter.py --onet --training_dir /tmp --do_push
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      is_permanent: false
      maxRestartCount: 0
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: rnet-grapth
    resources:
    - command: python3 movidius_converter.py --rnet --training_dir /tmp --do_push
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      is_permanent: false
      maxRestartCount: 0
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: fnet-grapth
    resources:
    - command: python3 movidius_converter.py --facenet --training_dir /tmp --do_push
        --model_base_path $MODEL_DIR
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      is_permanent: false
      maxRestartCount: 0
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: facenet-grapth
    resources:
    - command: python3 movidius_converter.py --all --training_dir /tmp --do_push --model_base_path
        $MODEL_DIR
      default_volume_mapping: true
      images:
        cpu: kuberlab/movidius-test:latest
        gpu: ""
      is_permanent: false
      maxRestartCount: 0
      name: worker
      nodes: knode:movidius
      replicas: 1
      resources:
        accelerators:
          gpu: 0
        limits:
          cpu: "1"
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 8Gi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
        requests:
          cpu: 100m
          cpu_mi: 0
          execution_time: 0
          gpu: 0
          memory: 64Mi
          memory_mb: 0
          parallel_runs: 0
          replicas: 0
      restartPolicy: Never
      workDir: $SRC_DIR
  uix:
  - default_volume_mapping: true
    disabled: false
    displayName: Jupyter
    images:
      cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
      gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
    name: jupyter
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    resources:
      accelerators:
        gpu: 0
      limits:
        cpu: "1"
        cpu_mi: 0
        execution_time: 0
        gpu: 0
        memory: 4Gi
        memory_mb: 0
        parallel_runs: 0
        replicas: 0
      requests:
        cpu: 101m
        cpu_mi: 0
        execution_time: 0
        gpu: 0
        memory: 64Mi
        memory_mb: 0
        parallel_runs: 0
        replicas: 0
  volumes:
  - clusterStorage: '{{ .storage.value }}'
    isLibDir: false
    isTrainLogDir: false
    isWorkspaceLocal: false
    mountPath: ""
    name: training
    readOnly: false
    subPath: ""
  - gitRepo:
      repository: https://github.com/kuberlab/facenet
    isLibDir: false
    isTrainLogDir: false
    isWorkspaceLocal: false
    mountPath: ""
    name: src
    readOnly: false
    subPath: facenet/src
  - clusterStorage: '{{ .storage.value }}'
    isLibDir: true
    isTrainLogDir: false
    isWorkspaceLocal: false
    mountPath: ""
    name: lib
    readOnly: false
    subPath: ""
  - clusterStorage: '{{ .storage.value }}'
    isLibDir: false
    isTrainLogDir: false
    isWorkspaceLocal: false
    mountPath: /notebooks
    name: code
    readOnly: false
    subPath: code
  - datasetFS:
      dataset: facenet-pretrained
      version: 2018.4.2-vgg
      workspace: kuberlab-demo
    isLibDir: false
    isTrainLogDir: false
    isWorkspaceLocal: false
    mountPath: ""
    name: model
    readOnly: false
    subPath: ""