
storage:
 value: default
 wizard:
   name: "Storage Configuration"
   kind: cluster_storage

tensorflow_version:
  value: "1.7.0"
  wizard:
    name: "Tensorflow version"
    kind: select
    options:
    - "1.2.0"
    - "1.3.0"
    - "1.4.0"
    - "1.5.0"
    - "1.6.0"
    - "1.7.0"
    - "latest"

python_version:
  value: "3"
  wizard:
    name: "Python version"
    kind: select
    options:
    - "2"
    - "3"

src:
  value: https://github.com/kuberlab/facenet
  wizard:
    name: "Source Code"
    kind: git

dataset:
 value: 'facenet-pretrained'
 version: '2018.4.2-vgg'
 workspace: 'kuberlab-demo'
 wizard:
   name: "Dataset configuration"
   kind: dataset


faces:
 value: 'faces'
 version: '1.0.1'
 workspace: 'kuberlab-demo'
 wizard:
   name: "Faces dataset configuration"
   kind: dataset
